<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = '2021-08-02 09:00:00';
        \DB::table('employees')->delete();

        \DB::table('employees')->insert([
                [
                    'emp_no' => '2103080001',
                    'fname' => 'แอดมิน',
                    'lname' => 'ระบบ (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000001',
                    'citizen_no' => '1300000000001',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 1,
                ],
            //คอสเม่
                [
                    'emp_no' => '2103080002',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายคลัง (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000002',
                    'citizen_no' => '1300000000002',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2103080003',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายตรวจสอบ (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000003',
                    'citizen_no' => '1300000000003',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2103080004',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายผลิต (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000004',
                    'citizen_no' => '1300000000004',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2103080005',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายจัดซื้อ (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000005',
                    'citizen_no' => '1300000000005',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2103080006',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายควบคุมคุณภาพ (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000006',
                    'citizen_no' => '1300000000006',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2103080007',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายขนส่ง (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000007',
                    'citizen_no' => '1300000000007',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2103080008',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายบัญชี (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000008',
                    'citizen_no' => '1300000000008',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 1,
                ],

                //กรีนฟาร์ม
                [
                    'emp_no' => '2103080009',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายคลัง (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000009',
                    'citizen_no' => '1300000000009',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2103080010',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายตรวจสอบ (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000010',
                    'citizen_no' => '1300000000010',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2103080011',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายผลิต (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000011',
                    'citizen_no' => '1300000000011',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2103080012',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายจัดซื้อ (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000012',
                    'citizen_no' => '1300000000012',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2103080013',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายควบคุมคุณภาพ (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000013',
                    'citizen_no' => '1300000000013',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2103080014',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายขนส่ง (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000014',
                    'citizen_no' => '1300000000014',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2103080015',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายบัญชี (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000015',
                    'citizen_no' => '1300000000015',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 2,
                ],
                //อินโนเวชั่น
                [
                    'emp_no' => '2103080016',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายคลัง (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000016',
                    'citizen_no' => '1300000000016',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 3,
                ],
                [
                    'emp_no' => '2103080017',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายตรวจสอบ (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000017',
                    'citizen_no' => '1300000000017',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 3,
                ],
                [
                    'emp_no' => '2103080018',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายผลิต (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000018',
                    'citizen_no' => '1300000000018',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 3,
                ],
                [
                    'emp_no' => '2103080019',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายจัดซื้อ (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000019',
                    'citizen_no' => '1300000000019',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 3,
                ],
                [
                    'emp_no' => '2103080020',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายควบคุมคุณภาพ (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000020',
                    'citizen_no' => '1300000000020',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 3,
                ],
                [
                    'emp_no' => '2103080021',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายขนส่ง (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000021',
                    'citizen_no' => '1300000000021',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 3,
                ],
                [
                    'emp_no' => '2103080022',
                    'fname' => 'หัวหน้า',
                    'lname' => 'ฝ่ายบัญชี (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000022',
                    'citizen_no' => '1300000000022',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 3,
                ],

                //ชุดใหม่
                //ดูสต็อก
                [
                    'emp_no' => '2203290001',
                    'fname' => 'หน่วย',
                    'lname' => 'ดูสต็อก (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000023',
                    'citizen_no' => '1300000000023',
                    'record_status' => 1,
                    'prefix_id' => 3,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2203290002',
                    'fname' => 'หน่วย',
                    'lname' => 'ดูสต็อก (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000024',
                    'citizen_no' => '1300000000024',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2203290003',
                    'fname' => 'หน่วย',
                    'lname' => 'ดูสต็อก (บริษัท ออแกนิค อินโนเวชั่น)',
                    'tel' => '0800000025',
                    'citizen_no' => '1300000000025',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 3,
                ],
                //packaging supply
                [
                    'emp_no' => '2203290004',
                    'fname' => 'หน่วย',
                    'lname' => 'บรรจุภัณฑ์และวัสดุสิ้นเปลือง (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000026',
                    'citizen_no' => '1300000000026',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2203290005',
                    'fname' => 'หน่วย',
                    'lname' => 'บรรจุภัณฑ์และวัสดุสิ้นเปลือง (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000027',
                    'citizen_no' => '1300000000027',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2203290006',
                    'fname' => 'หน่วย',
                    'lname' => 'บรรจุภัณฑ์และวัสดุสิ้นเปลือง (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000028',
                    'citizen_no' => '1300000000028',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 3,
                ],
                //material
                [
                    'emp_no' => '2203290007',
                    'fname' => 'หน่วย',
                    'lname' => 'วัตถุดิบ (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000029',
                    'citizen_no' => '1300000000029',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2203290008',
                    'fname' => 'หน่วย',
                    'lname' => 'วัตถุดิบ (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000030',
                    'citizen_no' => '1300000000030',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2203290009',
                    'fname' => 'หน่วย',
                    'lname' => 'วัตถุดิบ (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000031',
                    'citizen_no' => '1300000000031',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 3,
                ],
                //finish product
                [
                    'emp_no' => '2203290010',
                    'fname' => 'หน่วย',
                    'lname' => 'สินค้าสำเร็จรูป (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000032',
                    'citizen_no' => '1300000000032',
                    'record_status' => 1,
                    'prefix_id' => 2,
                    'company_id' => 1,
                ],
                [
                    'emp_no' => '2203290011',
                    'fname' => 'หน่วย',
                    'lname' => 'สินค้าสำเร็จรูป (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000033',
                    'citizen_no' => '1300000000033',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2203290012',
                    'fname' => 'หน่วย',
                    'lname' => 'สินค้าสำเร็จรูป (บริษัท ออแกนิค คอสเม่)',
                    'tel' => '0800000034',
                    'citizen_no' => '1300000000034',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 3,
                ],
                [
                    'emp_no' => '2203290013',
                    'fname' => 'หน่วย',
                    'lname' => 'ฝ่ายตรวจสอบวัตถุดิบ (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000035',
                    'citizen_no' => '1300000000035',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2203290014',
                    'fname' => 'หน่วย',
                    'lname' => 'ฝ่ายตรวจสอบบรรจุภัณฑ์ (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000036',
                    'citizen_no' => '1300000000036',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2203290015',
                    'fname' => 'หน่วย',
                    'lname' => 'ดูสต็อกวัตถุดิบ (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000037',
                    'citizen_no' => '1300000000037',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
                [
                    'emp_no' => '2203290016',
                    'fname' => 'หน่วย',
                    'lname' => 'ดูสต็อกบรรจุภัณฑ์ (บริษัท ออแกนิค กรีนฟาร์ม)',
                    'tel' => '0800000038',
                    'citizen_no' => '1300000000038',
                    'record_status' => 1,
                    'prefix_id' => 1,
                    'company_id' => 2,
                ],
            ]
        );
    }
}
